/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const EProductInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'condition' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const EProduct = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'sold' : IDL.Null,
    'available' : IDL.Null,
  }),
  'title' : IDL.Text,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'photos' : IDL.Vec(ExternalBlob),
  'condition' : IDL.Text,
});
export const RecyclerPrice = IDL.Record({
  'recycler' : IDL.Principal,
  'pricePerUnit' : IDL.Nat,
  'category' : IDL.Text,
});
export const Transaction = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  }),
  'recycler' : IDL.Principal,
  'productId' : IDL.Text,
  'seller' : IDL.Principal,
  'timestamp' : IDL.Int,
  'quantity' : IDL.Nat,
  'totalPrice' : IDL.Nat,
});
export const UserType = IDL.Variant({
  'recycler' : IDL.Null,
  'company' : IDL.Null,
  'individual' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'userType' : UserType,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'isVerified' : IDL.Bool,
});
export const CSRMetrics = IDL.Record({
  'co2Saved' : IDL.Nat,
  'materialsRecycled' : IDL.Nat,
  'totalItemsSold' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const EProductUpdate = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'description' : IDL.Text,
  'quantity' : IDL.Nat,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'photos' : IDL.Vec(ExternalBlob),
  'condition' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addProduct' : IDL.Func([EProductInput], [IDL.Text], []),
  'addToBasket' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'callersBasketQuantity' : IDL.Func(
      [IDL.Principal, IDL.Text],
      [IDL.Opt(IDL.Nat)],
      ['query'],
    ),
  'createTransaction' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
  'deleteProduct' : IDL.Func([IDL.Text], [], []),
  'getAllProducts' : IDL.Func([], [IDL.Vec(EProduct)], ['query']),
  'getAllRecyclerPrices' : IDL.Func([], [IDL.Vec(RecyclerPrice)], ['query']),
  'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
  'getCSRMetrics' : IDL.Func([], [CSRMetrics], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyRecyclerTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getMySellerTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
  'getProduct' : IDL.Func([IDL.Text], [EProduct], ['query']),
  'getProductsByStatus' : IDL.Func(
      [
        IDL.Variant({
          'pending' : IDL.Null,
          'sold' : IDL.Null,
          'available' : IDL.Null,
        }),
      ],
      [IDL.Vec(EProduct)],
      ['query'],
    ),
  'getRecyclerPrices' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(RecyclerPrice)],
      ['query'],
    ),
  'getTransaction' : IDL.Func([IDL.Text], [Transaction], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeFromBasket' : IDL.Func([IDL.Text], [], []),
  'revokeRecyclerVerification' : IDL.Func([IDL.Principal], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setRecyclerPrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
  'updateProduct' : IDL.Func([EProductUpdate], [], []),
  'updateTransactionStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Variant({
          'pending' : IDL.Null,
          'completed' : IDL.Null,
          'confirmed' : IDL.Null,
        }),
      ],
      [],
      [],
    ),
  'verifyRecycler' : IDL.Func([IDL.Principal], [], []),
  'viewBasket' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Tuple(EProduct, IDL.Nat)))],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const EProductInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'condition' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const EProduct = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'sold' : IDL.Null,
      'available' : IDL.Null,
    }),
    'title' : IDL.Text,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'photos' : IDL.Vec(ExternalBlob),
    'condition' : IDL.Text,
  });
  const RecyclerPrice = IDL.Record({
    'recycler' : IDL.Principal,
    'pricePerUnit' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Transaction = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'completed' : IDL.Null,
      'confirmed' : IDL.Null,
    }),
    'recycler' : IDL.Principal,
    'productId' : IDL.Text,
    'seller' : IDL.Principal,
    'timestamp' : IDL.Int,
    'quantity' : IDL.Nat,
    'totalPrice' : IDL.Nat,
  });
  const UserType = IDL.Variant({
    'recycler' : IDL.Null,
    'company' : IDL.Null,
    'individual' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'userType' : UserType,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'isVerified' : IDL.Bool,
  });
  const CSRMetrics = IDL.Record({
    'co2Saved' : IDL.Nat,
    'materialsRecycled' : IDL.Nat,
    'totalItemsSold' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const EProductUpdate = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'description' : IDL.Text,
    'quantity' : IDL.Nat,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'photos' : IDL.Vec(ExternalBlob),
    'condition' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addProduct' : IDL.Func([EProductInput], [IDL.Text], []),
    'addToBasket' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'callersBasketQuantity' : IDL.Func(
        [IDL.Principal, IDL.Text],
        [IDL.Opt(IDL.Nat)],
        ['query'],
      ),
    'createTransaction' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Text], []),
    'deleteProduct' : IDL.Func([IDL.Text], [], []),
    'getAllProducts' : IDL.Func([], [IDL.Vec(EProduct)], ['query']),
    'getAllRecyclerPrices' : IDL.Func([], [IDL.Vec(RecyclerPrice)], ['query']),
    'getAllTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(UserProfile)], ['query']),
    'getCSRMetrics' : IDL.Func([], [CSRMetrics], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyRecyclerTransactions' : IDL.Func(
        [],
        [IDL.Vec(Transaction)],
        ['query'],
      ),
    'getMySellerTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getMyTransactions' : IDL.Func([], [IDL.Vec(Transaction)], ['query']),
    'getProduct' : IDL.Func([IDL.Text], [EProduct], ['query']),
    'getProductsByStatus' : IDL.Func(
        [
          IDL.Variant({
            'pending' : IDL.Null,
            'sold' : IDL.Null,
            'available' : IDL.Null,
          }),
        ],
        [IDL.Vec(EProduct)],
        ['query'],
      ),
    'getRecyclerPrices' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(RecyclerPrice)],
        ['query'],
      ),
    'getTransaction' : IDL.Func([IDL.Text], [Transaction], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeFromBasket' : IDL.Func([IDL.Text], [], []),
    'revokeRecyclerVerification' : IDL.Func([IDL.Principal], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setRecyclerPrice' : IDL.Func([IDL.Text, IDL.Nat], [], []),
    'updateProduct' : IDL.Func([EProductUpdate], [], []),
    'updateTransactionStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Variant({
            'pending' : IDL.Null,
            'completed' : IDL.Null,
            'confirmed' : IDL.Null,
          }),
        ],
        [],
        [],
      ),
    'verifyRecycler' : IDL.Func([IDL.Principal], [], []),
    'viewBasket' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Tuple(EProduct, IDL.Nat)))],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };