/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CSRMetrics {
  'co2Saved' : bigint,
  'materialsRecycled' : bigint,
  'totalItemsSold' : bigint,
  'totalRevenue' : bigint,
}
export interface EProduct {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'sold' : null } |
    { 'available' : null },
  'title' : string,
  'owner' : Principal,
  'description' : string,
  'quantity' : bigint,
  'category' : string,
  'price' : bigint,
  'photos' : Array<ExternalBlob>,
  'condition' : string,
}
export interface EProductInput {
  'title' : string,
  'description' : string,
  'quantity' : bigint,
  'category' : string,
  'price' : bigint,
  'condition' : string,
}
export interface EProductUpdate {
  'id' : string,
  'title' : string,
  'description' : string,
  'quantity' : bigint,
  'category' : string,
  'price' : bigint,
  'photos' : Array<ExternalBlob>,
  'condition' : string,
}
export type ExternalBlob = Uint8Array;
export interface RecyclerPrice {
  'recycler' : Principal,
  'pricePerUnit' : bigint,
  'category' : string,
}
export interface Transaction {
  'id' : string,
  'status' : { 'pending' : null } |
    { 'completed' : null } |
    { 'confirmed' : null },
  'recycler' : Principal,
  'productId' : string,
  'seller' : Principal,
  'timestamp' : bigint,
  'quantity' : bigint,
  'totalPrice' : bigint,
}
export interface UserProfile {
  'id' : Principal,
  'userType' : UserType,
  'name' : string,
  'email' : string,
  'isVerified' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type UserType = { 'recycler' : null } |
  { 'company' : null } |
  { 'individual' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addProduct' : ActorMethod<[EProductInput], string>,
  'addToBasket' : ActorMethod<[string, bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'callersBasketQuantity' : ActorMethod<[Principal, string], [] | [bigint]>,
  'createTransaction' : ActorMethod<[string, bigint], string>,
  'deleteProduct' : ActorMethod<[string], undefined>,
  'getAllProducts' : ActorMethod<[], Array<EProduct>>,
  'getAllRecyclerPrices' : ActorMethod<[], Array<RecyclerPrice>>,
  'getAllTransactions' : ActorMethod<[], Array<Transaction>>,
  'getAllUsers' : ActorMethod<[], Array<UserProfile>>,
  'getCSRMetrics' : ActorMethod<[], CSRMetrics>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyRecyclerTransactions' : ActorMethod<[], Array<Transaction>>,
  'getMySellerTransactions' : ActorMethod<[], Array<Transaction>>,
  'getMyTransactions' : ActorMethod<[], Array<Transaction>>,
  'getProduct' : ActorMethod<[string], EProduct>,
  'getProductsByStatus' : ActorMethod<
    [{ 'pending' : null } | { 'sold' : null } | { 'available' : null }],
    Array<EProduct>
  >,
  'getRecyclerPrices' : ActorMethod<[string], Array<RecyclerPrice>>,
  'getTransaction' : ActorMethod<[string], Transaction>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'removeFromBasket' : ActorMethod<[string], undefined>,
  'revokeRecyclerVerification' : ActorMethod<[Principal], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setRecyclerPrice' : ActorMethod<[string, bigint], undefined>,
  'updateProduct' : ActorMethod<[EProductUpdate], undefined>,
  'updateTransactionStatus' : ActorMethod<
    [
      string,
      { 'pending' : null } |
        { 'completed' : null } |
        { 'confirmed' : null },
    ],
    undefined
  >,
  'verifyRecycler' : ActorMethod<[Principal], undefined>,
  'viewBasket' : ActorMethod<[], Array<[string, [EProduct, bigint]]>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];