/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0-beta.9.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface EProduct {
    id: string;
    status: Variant_pending_sold_available;
    title: string;
    owner: Principal;
    description: string;
    quantity: bigint;
    category: string;
    price: bigint;
    photos: Array<ExternalBlob>;
    condition: string;
}
export interface EProductUpdate {
    id: string;
    title: string;
    description: string;
    quantity: bigint;
    category: string;
    price: bigint;
    photos: Array<ExternalBlob>;
    condition: string;
}
export interface EProductInput {
    title: string;
    description: string;
    quantity: bigint;
    category: string;
    price: bigint;
    condition: string;
}
export interface RecyclerPrice {
    recycler: Principal;
    pricePerUnit: bigint;
    category: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CSRMetrics {
    co2Saved: bigint;
    materialsRecycled: bigint;
    totalItemsSold: bigint;
    totalRevenue: bigint;
}
export interface UserProfile {
    id: Principal;
    userType: UserType;
    name: string;
    email: string;
    isVerified: boolean;
}
export interface Transaction {
    id: string;
    status: Variant_pending_completed_confirmed;
    recycler: Principal;
    productId: string;
    seller: Principal;
    timestamp: bigint;
    quantity: bigint;
    totalPrice: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum UserType {
    recycler = "recycler",
    company = "company",
    individual = "individual"
}
export enum Variant_pending_completed_confirmed {
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum Variant_pending_sold_available {
    pending = "pending",
    sold = "sold",
    available = "available"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addProduct(product: EProductInput): Promise<string>;
    addToBasket(productId: string, quantity: bigint): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    callersBasketQuantity(caller: Principal, productId: string): Promise<bigint | null>;
    createTransaction(productId: string, quantity: bigint): Promise<string>;
    deleteProduct(productId: string): Promise<void>;
    getAllProducts(): Promise<Array<EProduct>>;
    getAllRecyclerPrices(): Promise<Array<RecyclerPrice>>;
    getAllTransactions(): Promise<Array<Transaction>>;
    getAllUsers(): Promise<Array<UserProfile>>;
    getCSRMetrics(): Promise<CSRMetrics>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getMyRecyclerTransactions(): Promise<Array<Transaction>>;
    getMySellerTransactions(): Promise<Array<Transaction>>;
    getMyTransactions(): Promise<Array<Transaction>>;
    getProduct(productId: string): Promise<EProduct>;
    getProductsByStatus(status: Variant_pending_sold_available): Promise<Array<EProduct>>;
    getRecyclerPrices(category: string): Promise<Array<RecyclerPrice>>;
    getTransaction(transactionId: string): Promise<Transaction>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    removeFromBasket(productId: string): Promise<void>;
    revokeRecyclerVerification(recyclerPrincipal: Principal): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setRecyclerPrice(category: string, pricePerUnit: bigint): Promise<void>;
    updateProduct(product: EProductUpdate): Promise<void>;
    updateTransactionStatus(transactionId: string, newStatus: Variant_pending_completed_confirmed): Promise<void>;
    verifyRecycler(recyclerPrincipal: Principal): Promise<void>;
    viewBasket(): Promise<Array<[string, [EProduct, bigint]]>>;
}
import type { EProduct as _EProduct, EProductUpdate as _EProductUpdate, ExternalBlob as _ExternalBlob, Transaction as _Transaction, UserProfile as _UserProfile, UserRole as _UserRole, UserType as _UserType, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this.uploadFile, this.downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this.uploadFile, this.downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addProduct(arg0: EProductInput): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0);
            return result;
        }
    }
    async addToBasket(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addToBasket(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToBasket(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async callersBasketQuantity(arg0: Principal, arg1: string): Promise<bigint | null> {
        if (this.processError) {
            try {
                const result = await this.actor.callersBasketQuantity(arg0, arg1);
                return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.callersBasketQuantity(arg0, arg1);
            return from_candid_opt_n7(this.uploadFile, this.downloadFile, result);
        }
    }
    async createTransaction(arg0: string, arg1: bigint): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createTransaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTransaction(arg0, arg1);
            return result;
        }
    }
    async deleteProduct(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllProducts(): Promise<Array<EProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllRecyclerPrices(): Promise<Array<RecyclerPrice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRecyclerPrices();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRecyclerPrices();
            return result;
        }
    }
    async getAllTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllTransactions();
                return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllTransactions();
            return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return from_candid_vec_n20(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCSRMetrics(): Promise<CSRMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getCSRMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCSRMetrics();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n26(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n26(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMyRecyclerTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyRecyclerTransactions();
                return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyRecyclerTransactions();
            return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMySellerTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMySellerTransactions();
                return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMySellerTransactions();
            return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getMyTransactions(): Promise<Array<Transaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyTransactions();
                return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyTransactions();
            return from_candid_vec_n16(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProduct(arg0: string): Promise<EProduct> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_EProduct_n11(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_EProduct_n11(this.uploadFile, this.downloadFile, result);
        }
    }
    async getProductsByStatus(arg0: Variant_pending_sold_available): Promise<Array<EProduct>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductsByStatus(to_candid_variant_n28(this.uploadFile, this.downloadFile, arg0));
                return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductsByStatus(to_candid_variant_n28(this.uploadFile, this.downloadFile, arg0));
            return from_candid_vec_n10(this.uploadFile, this.downloadFile, result);
        }
    }
    async getRecyclerPrices(arg0: string): Promise<Array<RecyclerPrice>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRecyclerPrices(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRecyclerPrices(arg0);
            return result;
        }
    }
    async getTransaction(arg0: string): Promise<Transaction> {
        if (this.processError) {
            try {
                const result = await this.actor.getTransaction(arg0);
                return from_candid_Transaction_n17(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTransaction(arg0);
            return from_candid_Transaction_n17(this.uploadFile, this.downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n25(this.uploadFile, this.downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async removeFromBasket(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromBasket(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromBasket(arg0);
            return result;
        }
    }
    async revokeRecyclerVerification(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeRecyclerVerification(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeRecyclerVerification(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n29(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n29(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async setRecyclerPrice(arg0: string, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setRecyclerPrice(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setRecyclerPrice(arg0, arg1);
            return result;
        }
    }
    async updateProduct(arg0: EProductUpdate): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(await to_candid_EProductUpdate_n33(this.uploadFile, this.downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(await to_candid_EProductUpdate_n33(this.uploadFile, this.downloadFile, arg0));
            return result;
        }
    }
    async updateTransactionStatus(arg0: string, arg1: Variant_pending_completed_confirmed): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateTransactionStatus(arg0, to_candid_variant_n37(this.uploadFile, this.downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateTransactionStatus(arg0, to_candid_variant_n37(this.uploadFile, this.downloadFile, arg1));
            return result;
        }
    }
    async verifyRecycler(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyRecycler(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyRecycler(arg0);
            return result;
        }
    }
    async viewBasket(): Promise<Array<[string, [EProduct, bigint]]>> {
        if (this.processError) {
            try {
                const result = await this.actor.viewBasket();
                return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.viewBasket();
            return from_candid_vec_n38(this.uploadFile, this.downloadFile, result);
        }
    }
}
async function from_candid_EProduct_n11(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EProduct): Promise<EProduct> {
    return await from_candid_record_n12(uploadFile, downloadFile, value);
}
async function from_candid_ExternalBlob_n15(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await downloadFile(value);
}
function from_candid_Transaction_n17(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Transaction): Transaction {
    return from_candid_record_n18(uploadFile, downloadFile, value);
}
function from_candid_UserProfile_n21(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n22(uploadFile, downloadFile, value);
}
function from_candid_UserRole_n26(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(uploadFile, downloadFile, value);
}
function from_candid_UserType_n23(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserType): UserType {
    return from_candid_variant_n24(uploadFile, downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(uploadFile, downloadFile, value);
}
function from_candid_opt_n25(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n21(uploadFile, downloadFile, value[0]);
}
function from_candid_opt_n6(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        sold: null;
    } | {
        available: null;
    };
    title: string;
    owner: Principal;
    description: string;
    quantity: bigint;
    category: string;
    price: bigint;
    photos: Array<_ExternalBlob>;
    condition: string;
}): Promise<{
    id: string;
    status: Variant_pending_sold_available;
    title: string;
    owner: Principal;
    description: string;
    quantity: bigint;
    category: string;
    price: bigint;
    photos: Array<ExternalBlob>;
    condition: string;
}> {
    return {
        id: value.id,
        status: from_candid_variant_n13(uploadFile, downloadFile, value.status),
        title: value.title,
        owner: value.owner,
        description: value.description,
        quantity: value.quantity,
        category: value.category,
        price: value.price,
        photos: await from_candid_vec_n14(uploadFile, downloadFile, value.photos),
        condition: value.condition
    };
}
function from_candid_record_n18(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: {
        pending: null;
    } | {
        completed: null;
    } | {
        confirmed: null;
    };
    recycler: Principal;
    productId: string;
    seller: Principal;
    timestamp: bigint;
    quantity: bigint;
    totalPrice: bigint;
}): {
    id: string;
    status: Variant_pending_completed_confirmed;
    recycler: Principal;
    productId: string;
    seller: Principal;
    timestamp: bigint;
    quantity: bigint;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        status: from_candid_variant_n19(uploadFile, downloadFile, value.status),
        recycler: value.recycler,
        productId: value.productId,
        seller: value.seller,
        timestamp: value.timestamp,
        quantity: value.quantity,
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n22(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    userType: _UserType;
    name: string;
    email: string;
    isVerified: boolean;
}): {
    id: Principal;
    userType: UserType;
    name: string;
    email: string;
    isVerified: boolean;
} {
    return {
        id: value.id,
        userType: from_candid_UserType_n23(uploadFile, downloadFile, value.userType),
        name: value.name,
        email: value.email,
        isVerified: value.isVerified
    };
}
function from_candid_record_n5(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(uploadFile, downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(uploadFile, downloadFile, value.topped_up_amount))
    };
}
async function from_candid_tuple_n39(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [string, [_EProduct, bigint]]): Promise<[string, [EProduct, bigint]]> {
    return [
        value[0],
        await from_candid_tuple_n40(uploadFile, downloadFile, value[1])
    ];
}
async function from_candid_tuple_n40(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [_EProduct, bigint]): Promise<[EProduct, bigint]> {
    return [
        await from_candid_EProduct_n11(uploadFile, downloadFile, value[0]),
        value[1]
    ];
}
function from_candid_variant_n13(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    sold: null;
} | {
    available: null;
}): Variant_pending_sold_available {
    return "pending" in value ? Variant_pending_sold_available.pending : "sold" in value ? Variant_pending_sold_available.sold : "available" in value ? Variant_pending_sold_available.available : value;
}
function from_candid_variant_n19(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): Variant_pending_completed_confirmed {
    return "pending" in value ? Variant_pending_completed_confirmed.pending : "completed" in value ? Variant_pending_completed_confirmed.completed : "confirmed" in value ? Variant_pending_completed_confirmed.confirmed : value;
}
function from_candid_variant_n24(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    recycler: null;
} | {
    company: null;
} | {
    individual: null;
}): UserType {
    return "recycler" in value ? UserType.recycler : "company" in value ? UserType.company : "individual" in value ? UserType.individual : value;
}
function from_candid_variant_n27(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n10(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EProduct>): Promise<Array<EProduct>> {
    return await Promise.all(value.map(async (x)=>await from_candid_EProduct_n11(uploadFile, downloadFile, x)));
}
async function from_candid_vec_n14(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n15(uploadFile, downloadFile, x)));
}
function from_candid_vec_n16(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Transaction>): Array<Transaction> {
    return value.map((x)=>from_candid_Transaction_n17(uploadFile, downloadFile, x));
}
function from_candid_vec_n20(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n21(uploadFile, downloadFile, x));
}
async function from_candid_vec_n38(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[string, [_EProduct, bigint]]>): Promise<Array<[string, [EProduct, bigint]]>> {
    return await Promise.all(value.map(async (x)=>await from_candid_tuple_n39(uploadFile, downloadFile, x)));
}
async function to_candid_EProductUpdate_n33(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EProductUpdate): Promise<_EProductUpdate> {
    return await to_candid_record_n34(uploadFile, downloadFile, value);
}
async function to_candid_ExternalBlob_n36(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await uploadFile(value);
}
function to_candid_UserProfile_n29(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n30(uploadFile, downloadFile, value);
}
function to_candid_UserRole_n8(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(uploadFile, downloadFile, value);
}
function to_candid_UserType_n31(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): _UserType {
    return to_candid_variant_n32(uploadFile, downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(uploadFile, downloadFile, value);
}
function to_candid_opt_n1(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(uploadFile, downloadFile, value));
}
function to_candid_record_n3(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n30(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    userType: UserType;
    name: string;
    email: string;
    isVerified: boolean;
}): {
    id: Principal;
    userType: _UserType;
    name: string;
    email: string;
    isVerified: boolean;
} {
    return {
        id: value.id,
        userType: to_candid_UserType_n31(uploadFile, downloadFile, value.userType),
        name: value.name,
        email: value.email,
        isVerified: value.isVerified
    };
}
async function to_candid_record_n34(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    description: string;
    quantity: bigint;
    category: string;
    price: bigint;
    photos: Array<ExternalBlob>;
    condition: string;
}): Promise<{
    id: string;
    title: string;
    description: string;
    quantity: bigint;
    category: string;
    price: bigint;
    photos: Array<_ExternalBlob>;
    condition: string;
}> {
    return {
        id: value.id,
        title: value.title,
        description: value.description,
        quantity: value.quantity,
        category: value.category,
        price: value.price,
        photos: await to_candid_vec_n35(uploadFile, downloadFile, value.photos),
        condition: value.condition
    };
}
function to_candid_variant_n28(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_sold_available): {
    pending: null;
} | {
    sold: null;
} | {
    available: null;
} {
    return value == Variant_pending_sold_available.pending ? {
        pending: null
    } : value == Variant_pending_sold_available.sold ? {
        sold: null
    } : value == Variant_pending_sold_available.available ? {
        available: null
    } : value;
}
function to_candid_variant_n32(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserType): {
    recycler: null;
} | {
    company: null;
} | {
    individual: null;
} {
    return value == UserType.recycler ? {
        recycler: null
    } : value == UserType.company ? {
        company: null
    } : value == UserType.individual ? {
        individual: null
    } : value;
}
function to_candid_variant_n37(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_pending_completed_confirmed): {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == Variant_pending_completed_confirmed.pending ? {
        pending: null
    } : value == Variant_pending_completed_confirmed.completed ? {
        completed: null
    } : value == Variant_pending_completed_confirmed.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n9(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n35(uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n36(uploadFile, downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, uploadFile, downloadFile, options.processError);
}
